version: "3.9"

services:
  db:
    image: mongodb
    volumes:
      - /usr/local/mongodb:/todo
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/poochshop
    ports:
      - "8000:8000"
    depends_on:
      - db