# Generated by Django 2.2.26 on 2022-04-07 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetFormData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('amount_spent', models.CharField(choices=[('LT100', 'less than 1000'), ('BET1000TO3000', '₹1000-₹3000'), ('BET3000TO5000', '₹3000-₹5000'), ('MT500', 'more than ₹5000')], max_length=100)),
                ('pincode', models.CharField(max_length=15)),
                ('services_required', models.CharField(choices=[('pet_grooming', 'Pet Grooming'), ('pet_sitting', 'Pet Sitting'), ('vet', 'Vet/At home vet'), ('pet_hostel', 'Pet hostel'), ('food_delivery', 'Home-made food delivery'), ('pet_taxi', 'Pet Taxi'), ('pet_party', 'Pet Party')], max_length=100)),
                ('auth_user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
