# Generated by Django 2.2.26 on 2022-04-07 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poochshop_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petformdata',
            name='auth_user_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
